# Generated by Django 2.1.5 on 2022-03-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20220322_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Course Title',
            },
        ),
        migrations.CreateModel(
            name='desc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desc', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Description',
            },
        ),
        migrations.CreateModel(
            name='startDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('date', models.IntegerField(default=2022)),
            ],
            options={
                'verbose_name_plural': 'Course Title',
            },
        ),
    ]
