# Generated by Django 2.1.5 on 2022-03-22 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_coursetitle_desc_startdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startdate',
            options={'verbose_name_plural': 'Start Date'},
        ),
        migrations.RenameField(
            model_name='desc',
            old_name='Desc',
            new_name='name',
        ),
    ]
